- name: Synchronization of backup-restore folder on the control machine to dest on the remote hosts
  ansible.posix.synchronize:
    src: ../src/debian/backup-restore/
    dest: /usr/local/bin/
    rsync_opts:
      - "--chown=root:root"

- name: Copy vimrc.local file
  ansible.builtin.copy:
    src: ../src/debian/vimrc.local
    dest: /etc/vim/vimrc.local
    mode: '0644'

- name: create /var/log/syslog-ng folder on hosts
  file:
    path: /var/log/syslog-ng
    state: directory
    mode: '0755'
- name: Copy syslog-ng conf file
  template:
    src: ../templates/syslog-ng.conf.j2
    dest: /etc/syslog-ng/syslog-ng.conf
    mode: '0644'
  notify: restart syslog-ng
- block:
  - name: Create /etc/syslog-ng/cert.d
    file:
      path: /etc/syslog-ng/cert.d
      state: directory
      mode: '0755'
  - name: Create /etc/syslog-ng/ca.d
    file:
      path: /etc/syslog-ng/ca.d/
      state: directory
      mode: '0755'
  - name: copy syslog client certificate
    ansible.builtin.copy:
      src: "{{ syslog_tls_ca }}"
      dest: /etc/syslog-ng/cert.d/clientcert.pem
      mode: '0644'
  - name: copy syslog key
    ansible.builtin.copy:
      src: "{{ syslog_tls_key }}"
      dest: /etc/syslog-ng/cert.d/clientkey.pem
      mode: '0400'
  - name: copy syslog server ca
    ansible.builtin.copy:
      src: "{{ syslog_tls_server_ca }}"
      dest: /etc/syslog-ng/ca.d/serverca.pem
      mode: '0644'
  when:
    - syslog_tls_ca is defined
    - syslog_tls_key is defined
    - syslog_tls_server_ca is defined

- name: Install sudo virtu user rules
  copy:
    src: ../src/debian/sudoers/virtu
    dest: /etc/sudoers.d/virtu
    owner: root
    group: root
    mode: '0440'
- name: remove 'virtu' from sudoers file
  lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: '^virtu'
    validate: visudo -cf %s

- name: Copy journald conf file
  ansible.builtin.copy:
    src: ../src/debian/journald.conf
    dest: /etc/systemd/journald.conf
    mode: '0644'
  register: journaldconf
- name: Restart systemd-journald
  ansible.builtin.systemd:
    state: restarted
    name: systemd-journald
  when: journaldconf.changed

- name: Copy sysctl rules
  ansible.builtin.copy:
    src: ../src/debian/{{ item }}
    dest: /etc/sysctl.d/{{ item }}
    mode: '0644'
  with_items:
    - 00-panicreboot.conf

- name: customize /etc/environment
  ansible.builtin.lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  vars:
    env_list:
      HISTSIZE: 2000000
      HISTFILESIZE: 2000000
      LIBVIRT_DEFAULT_URI: "qemu:///system"
      HISTTIMEFORMAT: '"%F %T "'
  with_items: "{{ env_list | dict2items }}"

- name: "PATH for virtu user"
  lineinfile:
    dest: /home/virtu/.bash_profile
    regexp: '^export PATH'
    line: "export PATH=$PATH:/usr/sbin:/usr/local/sbin:/sbin"
    state: present
    create: yes
    owner: virtu
    group: virtu
    mode: '0644'

- block:
    - name: Remove all file in /etc/apt/sources.list.d
      file:
        path: /etc/apt/sources.list.d
        state: absent
    - name: Configure apt repositories
      template:
        src: sources.list.j2
        dest: /etc/apt/sources.list
  when: apt_repo is defined

- name: "remove /etc/default/grub.d/*.cfg (FAI)"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ wildcard_files_to_delete.files }}"

- name: "grub conf"
  lineinfile:
    dest: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX=(?!.* {{ item }})\"[^\"]*)(\".*)"
    line: '\1 {{ item }}\2'
    state: present
    backrefs: yes
  register: updategrub1
  with_items:
    - ipv6.disable=1
    - efi=runtime
    - console=ttyS0,115200

- name: "grub conf osprober"
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_DISABLE_OS_PROBER=.*$'
    line: 'GRUB_DISABLE_OS_PROBER=true'
    state: present
  register: updategrub2
- name: update-grub
  command: update-grub
  when: updategrub1.changed or updategrub2.changed
