# Copyright (C) 2022, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0
---

- name: Remove hardened in SEAPATH Debian machines
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  vars:
    revert: true
  roles:
      - debian-hardening
